name: .NET build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    env:
      SOLUTION: ./<Solution name>.sln
    
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Update nuget.config with token
      run: dotnet nuget update source --source "https://nuget.pkg.github.com/kwtc/index.json" github --username kwtc --password "${{secrets.GITHUB_TOKEN}}" --store-password-in-clear-text
        
    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION -c Release --no-restore

    - name: Test
      run: dotnet test $SOLUTION -c Release --no-build --verbosity normal